[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
exclude = venv/

[mypy-src.*]
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-tests.*]
ignore_missing_imports = True
disable_error_code = no-untyped-def,no-any-return,empty-body